version: 2.1

yarn_cache_key: &yarn_cache_key
    v1-dependency-yarn-{{ checksum "package.json" }}
yarn_backup_cache_key: &yarn_backup_cache_key
    v1-dependency-yarn

restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *yarn_cache_key
        - *yarn_backup_cache_key

jobs:
    checkout_code:
        docker:
            - image: node:12.16.1
        steps:
            - *restore_repo
            - checkout
            - save_cache:
                key: v1-repo-{{ .Branch }}-{{ .Revision }}
                paths:
                    - .
    yarn_install:
        docker:
            - image: node:12.16.1
        steps:
            - *restore_repo
            - *restore_node_modules
            - run: yarn
            - save_cache:
                key: *yarn_cache_key
                paths:
                    - /root/project/node_modules
    test:
        docker:
            - image: node:12.16.1
        steps:
            - *restore_repo
            - *restore_node_modules
            - run: yarn test

workflows:
    install_and_test:
        jobs:
            - checkout_code
            - yarn_install:
                requires:
                    - checkout_code
            - test:
                requires:
                    - checkout_code
                    - yarn_install
